version: '3.9'

services:

  iots-postgres:
    image: postgis/postgis:15-3.3
    container_name: iots-postgres
    restart: always
    environment:
      POSTGRES_DB: iots_db
      POSTGRES_USER: iots_user
      POSTGRES_PASSWORD: /iots_pass@1
    ports:
      - "1000:5432"
    volumes:
      - iots_postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iots_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  iots-keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: iots-keycloak
    command: start-dev --http-enabled=true --hostname-strict=false
    restart: always
    environment:
      # All possible variants for the admin user
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      
      # Database configuration
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://iots-postgres:5432/iots_db
      KC_DB_USERNAME: iots_user
      KC_DB_PASSWORD: /iots_pass@1
      
      KC_LOG_LEVEL: INFO
    ports:
      - "1001:8080"
    depends_on:
      iots-postgres:
        condition: service_healthy

volumes:
  iots_postgres_data:
    name: iots_postgres_data